#!/usr/bin/env ruby

# Ferret DRb server launcher script
#
# place in script/ and start with script/runner script/ferret_server
# place doc/ferret_server.yml into RAILS_ROOT/config and fit to taste.
#
# to run the unit tests against the drb server, start it with
# RAILS_ENV=test script/runner script/ferret_server
# and run your tests with the AAF_REMOTE environment variable set to a
# non-empty value


ActsAsFerret::Remote::Server.start
DRb.thread.join


